### PR TITLE
Eiger4M AD3.3+

### PR DESCRIPTION
**Pull request by mrakitin**
This is a work done at CHX yesterday to enable support for `eiger4m_single` with the newer AD v3.3+ on the IOC (current version installed is 3.7 from @bsobhani).

### CODE REVIEW

**Review by awalter-bnl — APPROVED** [review]
Looks good to me, nice work @mrakitin

**Comment by mrakitin** [comment]
Thanks @awalter-bnl!

**Comment by tacaswell** [comment]
looks good! :shipit:

**Comment by mrakitin** [comment]
Thank you @tacaswell!

**Pull request merged**
