### PR TITLE
Modifying the areadetector definitions to work with AD33

### PR DESCRIPTION
**Pull request by awalter-bnl**
This is a PR that will allow for the detectors upgraded to AD33 to work with ophyd. It also adds the overlay plugin to the standard prosilica class

### CODE REVIEW

**Comment by mrakitin** [comment]
Looks good, let me know when it's ready for merging.

**Comment by awalter-bnl** [comment]
Thanks @mrakitin   this is just in preparation for the beamline visit tomorrow. I will merge it during the visit once I have had a chance to push any local changes up.

**Comment by licode** [comment]
LGTM 👍

**Comment by tacaswell** [comment]
When testing this some particular things to keep an eye on:

 - when running all of the plugins actually are set to non-blocking
 - that the 'wait for frames' PV really is flipped high!
 - see if you can arrange for some of the down-stream buffers to fill up (too much compression on a file plugin, make the process plugin pathological) and watch the timings that the status object really does not complete until the queue is drained

**Comment by awalter-bnl** [comment]
thanks @tacaswell I will check all of these

**Pull request merged**
